# Generated by Django 4.1.2 on 2022-10-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_subject_subjectname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(related_name='subjects', to='users.subject'),
        ),
    ]
